type Query {
  # getTopCubers(
  #   startDate: String!
  #   endDate: String!
  #   rank: Int!
  # ): [PersonEventReg!]!

  competition(id: String!): Competition
  competitions(week: Int, startDate: String, endDate: String): [Competition!]!
  person(wcaId: String!): Person
  results(weekYear: weekYear, eventId: String): [Result!]
}
