type Competition {
  id: ID!
  name: String!
  start_date: String!
  end_date: String!
  competitor_limit: Int!
  country_iso2: String!
  city: String!
  event_ids: [String!]!

  persons: [Person!]
}

type Person {
  name: String!
  wcaUserId: Int!
  wcaId: String
  countryIso2: String!
  registration: Registration
}

type Registration {
  status: String!
  eventIds: [String!]!
}

type PersonEventReg {
  name: String!
  wcaId: String
  countryIso2: String!
  eventId: String!
  single: Result
  average: Result
  competition: Comp!
}

type Result {
  value: Int!
  worldRanking: Int!
  continentalRanking: Int!
  nationalRanking: Int!
}

type Comp {
  id: String!
  name: String!
  startDate: String!
}

type Query {
  getCompetitions(startDate: String!, endDate: String!): [Competition!]!
  getTopCubers(
    startDate: String!
    endDate: String!
    rank: Int!
  ): [PersonEventReg!]!
}
