type User {
  id: Int!
  name: String!
  email: String!
  team: Team
}

type Team {
  id: Int!
  userId: Int!
  name: String!
  picks: [Pick!]
}

type Pick {
  id: Int!
  slot: Int!
  teamId: Int!
  week: Int!
  year: Int!
  wcaId: String!
  eventId: String!
  points: Int
}
